name: wake_guard
description: Ein Alarm, der nur über einen QR- oder NFC-Scan deaktiviert werden kann.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.6
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  flutter_nfc_kit: ^3.3.0
  shared_preferences: ^2.3.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
